<?php
require("../../Classes/PHPExcel.php");
 $objExcel= new PHPExcel;
 $objExcel->setActiveSheetIndex(0);
 $sheet=$objExcel->getActiveSheet()->setTitle('Table');
 $col=1;
 $sheet->setCellValue('B' .$col,'BẢNG THỐNG KÊ DOANH THU CỦA CỬA HÀNG');
 $col=2;
 $sheet->setCellValue('B' .$col,'Số Lượng Bán Được');
 $sheet->setCellValue('D' .$col,'Doanh Thu');
 $col=3;
 $sheet->setCellValue('A'.$col,'Tháng 1');
 $sheet->setCellValue('B' .$col,$_POST['SL1']);
 $sheet->setCellValue('D' .$col,$_POST['DThu1']);
 $col=4;
 $sheet->setCellValue('A'.$col,'Tháng 2');
 $sheet->setCellValue('B' .$col,$_POST['SL2']);
 $sheet->setCellValue('D' .$col,$_POST['DThu2']);
 $col=5;
 $sheet->setCellValue('A'.$col,'Tháng 3');
 $sheet->setCellValue('B' .$col,$_POST['SL3']);
 $sheet->setCellValue('D' .$col,$_POST['DThu3']);
 $col=6;
 $sheet->setCellValue('A'.$col,'Tháng 4');
 $sheet->setCellValue('B' .$col,$_POST['SL4']);
 $sheet->setCellValue('D' .$col,$_POST['DThu4']);
 $col=7;
 $sheet->setCellValue('A'.$col,'Tháng 5');
 $sheet->setCellValue('B' .$col,$_POST['SL5']);
 $sheet->setCellValue('D' .$col,$_POST['DThu5']);
 $col=8;
 $sheet->setCellValue('A'.$col,'Tháng 6');
 $sheet->setCellValue('B' .$col,$_POST['SL6']);
 $sheet->setCellValue('D' .$col,$_POST['DThu6']);
 $col=9;
 $sheet->setCellValue('A'.$col,'Tháng 7');
 $sheet->setCellValue('B' .$col,$_POST['SL7']);
 $sheet->setCellValue('D' .$col,$_POST['DThu7']);
 $col=10;
 $sheet->setCellValue('A'.$col,'Tháng 8');
 $sheet->setCellValue('B' .$col,$_POST['SL8']);
 $sheet->setCellValue('D' .$col,$_POST['DThu8']);
 $col=11;
 $sheet->setCellValue('A'.$col,'Tháng 9');
 $sheet->setCellValue('B' .$col,$_POST['SL9']);
 $sheet->setCellValue('D' .$col,$_POST['DThu9']);
 $col=12;
 $sheet->setCellValue('A'.$col,'Tháng 10');
 $sheet->setCellValue('B' .$col,$_POST['SL10']);
 $sheet->setCellValue('D' .$col,$_POST['DThu10']);
 $col=13;
 $sheet->setCellValue('A'.$col,'Tháng 11');
 $sheet->setCellValue('B' .$col,$_POST['SL11']);
 $sheet->setCellValue('D' .$col,$_POST['DThu11']);
 $col=14;
 $sheet->setCellValue('A'.$col,'Tháng 12');
 $sheet->setCellValue('B' .$col,$_POST['SL12']);
 $sheet->setCellValue('D' .$col,$_POST['DThu12']);
 
 
 $objWriter = new PHPExcel_Writer_Excel2007($objExcel);
 $filename='DoanhThuNam.xlsx';
 $objWriter->save($filename);
 ob_start();
 header('Content-Disposition: attachment; filename="' . $filename . '"');
 header('Content-Type: application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet');
 header('Content-Length: ' . filesize($filename));
 header('Content-Transfer-Encoding: binary');
 header('Cache-Control: must-revalidate');
 header('Pragma: no-cache');
 ob_end_flush();
 readfile($filename);
 return;
?>

